import { Inter, Roboto, Poppins } from 'next/font/google'
import './globals.css'
import Navbar from '@/componets/navbar/Navbar'
import Footer from '@/componets/footer/Footer'
import { ThemeContextProvider } from '../context/ThemeContext'
import AuthProvider from '@/componets/AuthProvider/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <AuthProvider>
          <div className='container'>
             <Navbar/>
             {children}
             <Footer/>
           </div>
           </AuthProvider>
        </ThemeContextProvider>
        </body>
    </html>
  )
}
